# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-02 19:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sib_order', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('figure', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('text', models.TextField(blank=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('sites', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=5)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='tree.MagicNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
