# Generated by Django 2.1.2 on 2018-11-05 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0005_auto_20181104_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
