# Generated by Django 2.1.2 on 2018-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20181109_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('D', 'директор'), ('W', 'Автор учебника'), ('Z', 'Учитель'), ('S', 'ученик'), ('P', 'родитель'), ('T', 'тьютор'), ('U', 'неизвестно')], default='U', max_length=1),
        ),
    ]
