# Generated by Django 2.1.2 on 2018-11-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='need_help',
            field=models.BooleanField(default=False),
        ),
    ]
