# Generated by Django 2.1.2 on 2018-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_exam_need_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
