# Generated by Django 2.1.2 on 2018-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0013_auto_20181113_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
