# Generated by Django 2.1.2 on 2018-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_auto_20181116_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
