# Generated by Django 2.1.2 on 2018-11-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_magicnode_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='far_away', to='tree.MagicNode'),
        ),
    ]
