# Generated by Django 2.1.2 on 2018-11-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_magicnode_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicnode',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='far_away', to='tree.MagicNode'),
        ),
    ]
