# Generated by Django 2.1.2 on 2018-11-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0017_auto_20181117_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
