# Generated by Django 2.1.2 on 2018-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0018_magicnode_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='date1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='date2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='fig_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='site1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
